"""
integrated_gradients.py
───────────────────────
Integrated Gradients (IG) attribution as a faithfulness robustness check
for the gradient saliency results reported in Table 8 of the manuscript.

Addresses GAP 3 from the JBI revision: gradient saliency has known
faithfulness limitations (Kindermans et al., 2019). IG (Sundararajan et al.,
2017) integrates gradients along a straight path from a zero-embedding
baseline to the input, providing attribution scores that satisfy the
completeness and sensitivity axioms. If IG produces the same near-zero
Jaccard similarity as gradient saliency, the near-zero finding is robust
across attribution methods — converting a "limitation" into a "robustness
check." If they disagree, both results are reported honestly.

Inputs
------
outputs/models/{model}/               — seed=42 checkpoints
outputs/results/shap/{model}_{platform}_{class}_top_words.csv
    Gradient-saliency top-K word sets (generated by code_A4_patch_attribution.py)
data/splits/cross_platform/test_{platform}.csv

Outputs
-------
outputs/results/ig_attribution_results.csv
    Per-(model, class, pair, K) Jaccard similarities for both methods.
    Columns: model, class_name, pair, k, jaccard_gradsal, jaccard_ig, agreement

outputs/results/ig_table8_update.csv
    Table 8 update: one row per (model, class, pair) at K=10,
    with both Grad-Sal J and IG J columns and an agreement flag.

outputs/results/shap/ig_{model}_{platform}_{class}_top_words.csv
    IG top-K word sets (mirrors the gradient saliency format).

Usage
-----
Run from the repository root:
    python src/integrated_gradients.py
    python src/integrated_gradients.py --model bert
    python src/integrated_gradients.py --n-samples 100   # faster testing

Dependencies
------------
Requires captum: pip install captum
Requires outputs/models/{model}/ checkpoints (run train.py first).
Requires outputs/results/shap/ CSVs (run code_A4_patch_attribution.py first).
"""

import os
import sys
import warnings
import argparse
from collections import defaultdict

import numpy as np
import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings(
    "ignore",
    message=".*captum.*",
    category=UserWarning,
)

sys.path.insert(0, os.path.dirname(__file__))
from utils import (
    MODELS,
    PLATFORMS,
    CLASSES,
    CLASS_IDS,
    MODEL_DISPLAY,
    load_config,
    get_model_checkpoint,
)

# ── Config ─────────────────────────────────────────────────────────────────────

cfg = load_config()

MODELS_DIR   = cfg["paths"]["models"]
RESULTS_DIR  = cfg["paths"]["results"]
SHAP_DIR     = os.path.join(RESULTS_DIR, "shap")
FAIRNESS_DIR = os.path.join(RESULTS_DIR, "fairness")
SPLITS_DIR   = "data/splits/cross_platform"

os.makedirs(FAIRNESS_DIR, exist_ok=True)

DEVICE       = torch.device("cuda" if torch.cuda.is_available() else "cpu")
N_SAMPLES    = 200       # texts per (platform, class) for attribution
N_STEPS      = 50        # IG integration steps (50 is sufficient for transformers)
INTERNAL_BS  = 4         # internal IG batch size (memory-safe for 8GB VRAM)
K_VALUES     = [5, 10, 15, 20]
MIN_FREQ     = 3         # minimum token occurrences to retain

LABEL_NAMES  = ["normal", "depression", "anxiety", "stress"]
PLATFORM_PAIRS = [
    ("kaggle", "reddit"),
    ("kaggle", "twitter"),
    ("reddit",  "twitter"),
]

# Vocabulary artifacts to filter (mirrors jaccard_full_analysis.py)
_ARTIFACTS = frozenset(
    ["NAME", "name", "hyp", "rified", "ing", "nt", "...", ""]
)
_SPECIALS = frozenset(
    ["[CLS]", "[SEP]", "[PAD]", "<s>", "</s>", "<pad>", "Ġ", "▁"]
)


# ── IG helper ──────────────────────────────────────────────────────────────────

def _get_embedding_layer(
    model: AutoModelForSequenceClassification,
    model_key: str,
) -> torch.nn.Module:
    """
    Return the word-embedding layer for LayerIntegratedGradients.

    BERT and RoBERTa variants expose their embedding layers through
    different attribute paths. We try the most common paths in order.

    Parameters
    ----------
    model : AutoModelForSequenceClassification
        The fine-tuned model.
    model_key : str
        One of MODELS — used only for informative error messages.

    Returns
    -------
    torch.nn.Module
        The word-embedding layer (nn.Embedding).

    Raises
    ------
    AttributeError
        If no known embedding path is found.
    """
    candidates = [
        "bert.embeddings.word_embeddings",
        "roberta.embeddings.word_embeddings",
        "distilbert.embeddings.word_embeddings",
        "base_model.embeddings.word_embeddings",
        "transformer.word_embeddings",
    ]
    for path in candidates:
        obj = model
        try:
            for attr in path.split("."):
                obj = getattr(obj, attr)
            return obj
        except AttributeError:
            continue

    # Fallback: look for any nn.Embedding whose size matches vocab
    for name, module in model.named_modules():
        if isinstance(module, torch.nn.Embedding) and module.num_embeddings > 1000:
            print(
                f"  [{model_key}] Using fallback embedding layer: {name} "
                f"(vocab={module.num_embeddings})"
            )
            return module

    raise AttributeError(
        f"Cannot find word-embedding layer for model key '{model_key}'. "
        "Supported architectures: BERT, RoBERTa, DistilBERT."
    )


def compute_ig_token_importance(
    model: AutoModelForSequenceClassification,
    tokenizer,
    model_key: str,
    texts: list[str],
    target_class_idx: int,
    n_steps: int = N_STEPS,
    internal_batch_size: int = INTERNAL_BS,
    max_length: int = 64,
) -> dict[str, float]:
    """
    Compute Integrated Gradients token attribution for a target class.

    Uses LayerIntegratedGradients on the word-embedding layer with a
    zero-embedding baseline (standard choice for NLP IG attribution).
    Attribution scores are the L2 norm of IG vectors summed across
    embedding dimensions, then averaged across occurrences of each token.

    Parameters
    ----------
    model : AutoModelForSequenceClassification
        Fine-tuned model in eval mode.
    tokenizer : AutoTokenizer
        Corresponding tokenizer.
    model_key : str
        Model key, used for embedding layer resolution.
    texts : list[str]
        Input texts to attribute.
    target_class_idx : int
        Class index for which attributions are computed.
    n_steps : int
        Number of IG integration steps. 50 is sufficient for convergence.
    internal_batch_size : int
        Internal batch size for the IG integral approximation.
        Lower values use less GPU memory.
    max_length : int
        Tokenizer truncation length.

    Returns
    -------
    dict[str, float]
        Mapping from cleaned token string to mean |IG| score,
        for tokens occurring at least MIN_FREQ times.
    """
    try:
        from captum.attr import LayerIntegratedGradients
    except ImportError as exc:
        raise ImportError(
            "captum is required for integrated_gradients.py.\n"
            "Install with: pip install captum"
        ) from exc

    model.eval()
    emb_layer = _get_embedding_layer(model, model_key)

    # IG forward function: takes input_ids (long), returns target-class logit
    def _forward_fn(input_ids: torch.Tensor) -> torch.Tensor:
        # attention_mask: 1 for all non-pad positions
        attn = (input_ids != tokenizer.pad_token_id).long()
        out  = model(input_ids=input_ids, attention_mask=attn)
        return out.logits[:, target_class_idx]

    lig = LayerIntegratedGradients(_forward_fn, emb_layer)

    word_scores: dict[str, list[float]] = defaultdict(list)
    n_success = 0

    for text in texts:
        enc = tokenizer(
            text,
            return_tensors="pt",
            max_length=max_length,
            padding="max_length",
            truncation=True,
        ).to(DEVICE)

        input_ids = enc["input_ids"]                         # (1, L)
        baseline  = torch.zeros_like(input_ids)              # zero-id baseline

        try:
            # LayerIntegratedGradients returns attributions in embedding space
            attrs, delta = lig.attribute(
                input_ids,
                baselines=baseline,
                target=None,           # target already baked into _forward_fn
                n_steps=n_steps,
                internal_batch_size=internal_batch_size,
                return_convergence_delta=True,
            )
            # attrs shape: (1, L, embed_dim)
            # Sum |IG| across embedding dimensions → (1, L)
            token_attrs = attrs[0].norm(dim=-1).detach().cpu().numpy()
            token_ids   = input_ids[0].cpu().numpy()
            tokens      = tokenizer.convert_ids_to_tokens(token_ids)

            for tok, score in zip(tokens, token_attrs):
                if tok in _SPECIALS:
                    continue
                clean = (
                    tok.lstrip("##").lstrip("Ġ").lstrip("▁").lower().strip()
                )
                if len(clean) > 1 and clean not in _ARTIFACTS:
                    word_scores[clean].append(float(score))

            n_success += 1

        except Exception as exc:  # noqa: BLE001
            # Skip samples that cause numerical issues
            _ = exc
            continue

    print(
        f"    IG computed for {n_success}/{len(texts)} samples "
        f"(class {LABEL_NAMES[target_class_idx]})"
    )
    return {
        w: float(np.mean(scores))
        for w, scores in word_scores.items()
        if len(scores) >= MIN_FREQ
    }


# ── Jaccard helpers ────────────────────────────────────────────────────────────

def top_k_words(scores: dict[str, float], k: int) -> set[str]:
    """Return the top-K words by attribution score as a frozenset."""
    if not scores:
        return set()
    sorted_words = sorted(scores.items(), key=lambda x: x[1], reverse=True)
    return {w for w, _ in sorted_words[:k]}


def jaccard(set_a: set[str], set_b: set[str]) -> float:
    """Compute Jaccard similarity between two sets. Returns 0 for empty sets."""
    if not set_a and not set_b:
        return 0.0
    union = set_a | set_b
    if not union:
        return 0.0
    return len(set_a & set_b) / len(union)


# ── Load gradient saliency top-K ──────────────────────────────────────────────

def load_gradsal_top_words(
    model_key: str,
    platform: str,
    class_name: str,
    k: int,
) -> set[str]:
    """
    Load gradient saliency top-K words from the pre-computed SHAP CSVs.

    Parameters
    ----------
    model_key : str
        One of MODELS.
    platform : str
        One of PLATFORMS.
    class_name : str
        One of CLASSES.
    k : int
        Number of top words to load.

    Returns
    -------
    set[str]
        Top-K words, or empty set if file is missing.
    """
    path = os.path.join(SHAP_DIR, f"{model_key}_{platform}_{class_name}_top_words.csv")
    if not os.path.exists(path):
        return set()
    try:
        df = pd.read_csv(path)
        # Convention: column named 'word' or first column
        col = "word" if "word" in df.columns else df.columns[0]
        return set(df[col].head(k).tolist())
    except Exception:  # noqa: BLE001
        return set()


# ── Main analysis ──────────────────────────────────────────────────────────────

def run_ig_analysis(
    target_models: list[str],
    n_samples: int = N_SAMPLES,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Run full IG attribution analysis for all models × classes × platforms.

    Parameters
    ----------
    target_models : list[str]
        Subset of MODELS to process.
    n_samples : int
        Number of texts to sample per (platform, class) for attribution.

    Returns
    -------
    tuple[pd.DataFrame, pd.DataFrame]
        ig_results_df : full Jaccard table across all K values
        table8_df     : Table 8 update at K=10
    """
    # Load test CSVs once
    test_dfs: dict[str, pd.DataFrame | None] = {}
    for platform in PLATFORMS:
        path = os.path.join(SPLITS_DIR, f"test_{platform}.csv")
        if os.path.exists(path):
            test_dfs[platform] = pd.read_csv(path)
        else:
            print(f"  WARNING: {path} not found — skipping {platform}")
            test_dfs[platform] = None

    ig_rows: list[dict]  = []
    t8_rows: list[dict]  = []
    ig_top_words: dict   = {}   # (model, platform, class_name) → {word: score}

    for model_key in target_models:
        display = MODEL_DISPLAY[model_key]
        print(f"\n{'='*60}")
        print(f"  Model: {display}")
        print(f"{'='*60}")

        ckpt = get_model_checkpoint(model_key, MODELS_DIR)
        if ckpt is None:
            print(f"  SKIP: No checkpoint found for {model_key}")
            continue

        tokenizer = AutoTokenizer.from_pretrained(ckpt)
        model     = AutoModelForSequenceClassification.from_pretrained(
            ckpt,
            num_labels=len(CLASSES),
            ignore_mismatched_sizes=True,
            problem_type="single_label_classification",
        ).to(DEVICE)
        model.eval()

        for class_name in CLASSES:
            class_idx = CLASS_IDS[class_name]
            print(f"\n  Class: {class_name} (idx={class_idx})")

            # ── Compute IG for each platform ───────────────────────────────
            platform_scores: dict[str, dict[str, float]] = {}

            for platform in PLATFORMS:
                df = test_dfs[platform]
                if df is None:
                    platform_scores[platform] = {}
                    continue

                # Sample up to n_samples texts for this class
                cls_df = df[df["label"] == class_idx]
                if len(cls_df) == 0:
                    platform_scores[platform] = {}
                    continue

                rng     = np.random.default_rng(seed=42 + class_idx)
                sampled = cls_df.sample(
                    min(n_samples, len(cls_df)),
                    random_state=int(rng.integers(0, 9999)),
                )
                texts   = sampled["text"].tolist()

                print(f"    {platform}: {len(texts)} texts")

                scores = compute_ig_token_importance(
                    model,
                    tokenizer,
                    model_key,
                    texts,
                    class_idx,
                )
                platform_scores[platform] = scores
                ig_top_words[(model_key, platform, class_name)] = scores

                # Save per-platform top-K CSV (mirrors gradient saliency format)
                if scores:
                    sorted_words = sorted(
                        scores.items(), key=lambda x: x[1], reverse=True
                    )
                    top_df = pd.DataFrame(sorted_words, columns=["word", "ig_score"])
                    out_path = os.path.join(
                        SHAP_DIR,
                        f"ig_{model_key}_{platform}_{class_name}_top_words.csv",
                    )
                    top_df.to_csv(out_path, index=False)

            # ── Compute Jaccard for all platform pairs × K values ──────────
            for pair in PLATFORM_PAIRS:
                src, tgt = pair
                pair_label = f"{src}→{tgt}"

                ig_src = platform_scores.get(src, {})
                ig_tgt = platform_scores.get(tgt, {})

                for k in K_VALUES:
                    ig_top_src = top_k_words(ig_src, k)
                    ig_top_tgt = top_k_words(ig_tgt, k)
                    j_ig       = jaccard(ig_top_src, ig_top_tgt)

                    # Load gradient saliency top-K for comparison
                    gs_src = load_gradsal_top_words(model_key, src, class_name, k)
                    gs_tgt = load_gradsal_top_words(model_key, tgt, class_name, k)
                    j_gs   = jaccard(gs_src, gs_tgt)

                    ig_rows.append({
                        "model":          model_key,
                        "class_name":     class_name,
                        "pair":           pair_label,
                        "k":              k,
                        "jaccard_gradsal": round(j_gs, 4),
                        "jaccard_ig":      round(j_ig, 4),
                    })

                # Build Table 8 entry at K=10
                k10 = 10
                ig_src10 = top_k_words(ig_src, k10)
                ig_tgt10 = top_k_words(ig_tgt, k10)
                j_ig10   = jaccard(ig_src10, ig_tgt10)

                gs_src10 = load_gradsal_top_words(model_key, src, class_name, k10)
                gs_tgt10 = load_gradsal_top_words(model_key, tgt, class_name, k10)
                j_gs10   = jaccard(gs_src10, gs_tgt10)

                # Agreement: "Consistent" if both near-zero (< 0.10)
                # "Disagree" if one method > 0.10 while the other ≤ 0.10
                if j_gs10 > 0.10 and j_ig10 > 0.10:
                    agreement = "Consistent (both high)"
                elif j_gs10 <= 0.10 and j_ig10 <= 0.10:
                    agreement = "Consistent (both near-zero)"
                else:
                    agreement = "Disagree"

                t8_rows.append({
                    "model":                 model_key,
                    "model_display":         display,
                    "class_name":            class_name,
                    "pair":                  pair_label,
                    "k":                     k10,
                    "jaccard_gradsal_k10":   round(j_gs10, 4),
                    "jaccard_ig_k10":        round(j_ig10, 4),
                    "agreement":             agreement,
                })

        del model
        torch.cuda.empty_cache()

    ig_results_df = pd.DataFrame(ig_rows)
    table8_df     = pd.DataFrame(t8_rows)
    return ig_results_df, table8_df


# ── Entry point ────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Integrated Gradients attribution for CPFE Table 8 update."
    )
    parser.add_argument(
        "--model",
        type=str,
        default="all",
        choices=["bert", "roberta", "mentalbert", "mentalroberta", "all"],
    )
    parser.add_argument(
        "--n-samples",
        type=int,
        default=N_SAMPLES,
        help=f"Texts per (platform, class). Default: {N_SAMPLES}.",
    )
    args = parser.parse_args()

    target_models = MODELS if args.model == "all" else [args.model]

    print(f"\nDevice  : {DEVICE}")
    if DEVICE.type == "cuda":
        print(f"GPU     : {torch.cuda.get_device_name(0)}")
    print(f"Models  : {target_models}")
    print(f"Samples : {args.n_samples} per (platform, class)")
    print(f"K values: {K_VALUES}")

    ig_results_df, table8_df = run_ig_analysis(target_models, args.n_samples)

    # Save outputs
    if not ig_results_df.empty:
        ig_path = os.path.join(RESULTS_DIR, "ig_attribution_results.csv")
        ig_results_df.to_csv(ig_path, index=False)
        print(f"\nIG results saved: {ig_path}  ({len(ig_results_df)} rows)")

    if not table8_df.empty:
        t8_path = os.path.join(RESULTS_DIR, "ig_table8_update.csv")
        table8_df.to_csv(t8_path, index=False)
        print(f"Table 8 update saved: {t8_path}  ({len(table8_df)} rows)")

        # Print Table 8 summary
        print(f"\n{'='*65}")
        print("TABLE 8 UPDATE (K=10) — Gradient Saliency J vs IG J")
        print(f"{'='*65}")
        print(
            f"{'Model':<22} {'Class':<12} {'Pair':<18} "
            f"{'Grad-Sal J':>10} {'IG J':>8} {'Agreement'}"
        )
        print("-" * 65)
        for _, row in table8_df.sort_values(
            ["model", "class_name", "pair"]
        ).iterrows():
            print(
                f"  {row['model_display']:<20} {row['class_name']:<12} "
                f"{row['pair']:<18} {row['jaccard_gradsal_k10']:>10.4f} "
                f"{row['jaccard_ig_k10']:>8.4f}  {row['agreement']}"
            )

        # Summary statistics
        consistent = (table8_df["agreement"].str.startswith("Consistent")).sum()
        total      = len(table8_df)
        print(f"\n  Consistent across methods: {consistent}/{total} "
              f"({100*consistent/total:.0f}%)")
        near_zero  = (table8_df["jaccard_ig_k10"] < 0.10).sum()
        print(f"  IG near-zero (J<0.10):     {near_zero}/{total}")

    print(f"\n{'='*60}")
    print("DONE — Integrated Gradients analysis complete.")
    print("Next step: python src/calibration_comparison.py")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
