"""
jaccard_full_analysis.py
────────────────────────
CPFE Axis 5: complete Jaccard attribution stability analysis at K∈{5,10,15,20}.

Computes Jaccard similarity between top-K gradient saliency vocabularies for
every model × platform pair (Kaggle↔Reddit, Kaggle↔Twitter, Reddit↔Twitter),
along with a random-baseline comparison and per-class clinical vocabulary
retention analysis.

Inputs
------
outputs/results/shap/{model}_{platform}_{class}_top_words.csv
    Top-K gradient saliency words per model, platform, and class.
    Generated by shap_analysis.py or code_A4_patch_attribution.py.

Outputs
-------
outputs/results/fairness/jaccard_full_analysis.csv
outputs/results/fairness/clinical_signal_retention.csv
outputs/figures/figure6_jaccard_with_baseline.png
outputs/figures/figure_clinical_vocabulary_heatmap.png

Usage
-----
Run from the repository root:
    python src/jaccard_full_analysis.py

Dependencies
------------
Requires code_A4_patch_attribution.py (or shap_analysis.py) to have been
run first.
"""

import os
import warnings
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns

from utils import MODELS, PLATFORMS, CLASSES, MODEL_DISPLAY, load_config

warnings.filterwarnings("ignore", category=FutureWarning)

cfg = load_config()

RESULTS_DIR  = cfg["paths"]["results"]
FIGURES_DIR  = cfg["paths"]["figures"]
FAIRNESS_DIR = os.path.join(RESULTS_DIR, "fairness")
os.makedirs(FAIRNESS_DIR, exist_ok=True)
os.makedirs(FIGURES_DIR,  exist_ok=True)

ACTIVE_MODELS    = MODELS
ATTRIBUTION_BASE = os.path.join(RESULTS_DIR, "shap")
K_VALUES         = [5, 10, 15, 20]

# Approximate vocabulary sizes (for random baseline)
VOCAB_SIZES = {
    "bert":          30522,   # BERT WordPiece
    "roberta":       50265,   # RoBERTa BPE
    "mentalbert":    50265,   # Hartmann DistilRoBERTa (RoBERTa tokenizer)
    "mentalroberta": 50265,   # SamLowe (RoBERTa tokenizer)
}

# ── Token filtering ───────────────────────────────────────────────────────────

ARTIFACTS = {
    "NAME", "name", "hyp", "rified", "ing", "nt", "...",
}

STOPWORDS = {
    "the", "and", "for", "not", "you", "this", "that", "was", "are",
    "have", "with", "but", "all", "from", "they", "can", "her", "his",
    "out", "one", "who", "its", "were", "how", "him", "had", "see",
    "just", "been", "more", "about", "over", "has", "she", "day",
    "when", "even", "what", "know", "your", "there", "then", "than",
    "into", "will", "could", "some", "them", "dont", "those", "our",
    "now", "did", "got", "too", "being", "also", "The", "And", "Its",
    "This", "dont", "get", "or", "it", "an", "if", "by", "to", "of",
    "in", "is", "we", "at", "he", "be", "my", "me", "up", "do", "so",
    "no", "as", "am", "us", "on", "don", "can", "look", "work", "more",
    "like", "feel", "every", "These", "Those", "Their", "While", "shit",
    "really", "good", "people", "man", "what", "sorry", "little", "its",
    "lame", "now", "bit", "because", "should", "time", "feels", "with",
}

CLINICAL_TERMS = {
    "anxiety", "depression", "stress", "trauma", "ptsd", "ocd", "adhd",
    "bipolar", "schizophrenia", "disorder", "mental", "health",
    "anxious", "nervous", "terrified", "afraid", "scared", "worried",
    "worry", "panic", "helpless", "hopeless", "worthless", "exhausted",
    "overwhelmed", "struggling", "burnout", "grief", "mourning",
    "insomnia", "sleep", "suicidal", "suicide",
    "therapy", "therapist", "medication", "medicine", "diagnosis",
    "symptom", "symptoms", "treatment", "counseling", "counsel",
    "psychiatrist", "psychologist", "clinical", "recovery", "relapse",
    "episode", "antidepressant",
    "relationship", "abuse", "trauma", "pain", "suffering",
    "loss", "loneliness", "isolated", "alone", "lonely",
    "self", "harm", "hurt", "cope", "coping", "crisis",
}


# ── Random Jaccard baseline ───────────────────────────────────────────────────

def expected_jaccard_random(K: int, vocab_size: int) -> float:
    """
    Expected Jaccard similarity of two independently drawn top-K sets
    from a vocabulary of size V:
        E[J] = K / (2K - K^2/V) ≈ K / (2K)  for V >> K
    More precisely (hypergeometric):
        E[J] = E[|A ∩ B|] / E[|A ∪ B|]
    where E[|A ∩ B|] = K^2 / V  (expected overlap of two K-sets from V)
          E[|A ∪ B|] = 2K - K^2/V

    Returns a value near 0 for large vocabularies and small K.
    """
    expected_intersection = (K ** 2) / vocab_size
    expected_union        = 2 * K - expected_intersection
    if expected_union <= 0:
        return 0.0
    return round(expected_intersection / expected_union, 6)


# ── Core Jaccard computation ──────────────────────────────────────────────────

def load_top_words(model_key: str, platform: str, class_name: str,
                   K: int, filter_artifacts: bool = False) -> set:
    """
    Load top-K attributed tokens for a model×platform×class combination.

    Searches in two directories:
      1. outputs/results/shap/   (produced by shap_analysis.py)
      2. outputs/results/attribution/  (produced by code_A4_patch_attribution.py)

    Returns an empty set if no file is found.
    """
    candidates = [
        os.path.join(RESULTS_DIR, "shap",
                     f"{model_key}_{platform}_{class_name}_top_words.csv"),
        os.path.join(RESULTS_DIR, "attribution",
                     f"{model_key}_{platform}_{class_name}_scores.csv"),
    ]

    df = None
    for path in candidates:
        if os.path.exists(path):
            df = pd.read_csv(path)
            break

    if df is None or df.empty:
        return set()

    # Normalise column names across all three file formats
    # (mean_gradient: new shap_analysis; mean_shap: old; mean_importance: A4)
    word_col  = "word" if "word" in df.columns else "token"
    score_col = next(
        (c for c in ["mean_gradient", "mean_shap", "mean_importance"]
         if c in df.columns),
        None,
    )

    if word_col not in df.columns or score_col is None:
        return set()

    df = df.sort_values(score_col, ascending=False)

    if filter_artifacts:
        df = df[~df[word_col].isin(ARTIFACTS | STOPWORDS)]

    return set(df[word_col].head(K).tolist())


def jaccard(set_a: set, set_b: set) -> float:
    """Jaccard similarity between two sets. Returns 0.0 if both empty."""
    union = set_a | set_b
    if not union:
        return float("nan")
    return round(len(set_a & set_b) / len(union), 4)


def clinical_signal_retention(word_set: set) -> float:
    """
    Fraction of words in word_set that appear in CLINICAL_TERMS.
    Measures how much clinical vocabulary is retained in the top-K attribution.
    """
    if not word_set:
        return float("nan")
    clinical_count = sum(1 for w in word_set if w.lower() in CLINICAL_TERMS)
    return round(clinical_count / len(word_set), 4)


def compute_within_platform_jaccard(
    model_key: str,
    class_name: str,
    K: int = 10,
) -> float:
    """
    Within-platform split-half Jaccard baseline for Kaggle attribution scores.

    Splits the Kaggle attribution CSV by score rank (odd rows vs even rows),
    takes the top-K from each half, and computes Jaccard similarity.  This
    is the critical baseline for interpreting cross-platform J values:

    - If within-Kaggle J >> cross-platform J → cross-platform collapse is real.
    - If within-Kaggle J is also near zero → low J is partly a vocabulary-size
      artefact; both same-platform and cross-platform rankings are sparse.

    Parameters
    ----------
    model_key : str
        One of ``MODELS``.
    class_name : str
        One of ``CLASSES``.
    K : int, optional
        Number of top words per half.  Default is 10.

    Returns
    -------
    float
        Jaccard similarity between the two split halves, or ``float("nan")``
        if the attribution file is not found or too small.
    """
    candidates = [
        os.path.join(RESULTS_DIR, "gradient_attribution",
                     f"{model_key}_kaggle_{class_name}_top_words.csv"),
        os.path.join(RESULTS_DIR, "shap",
                     f"{model_key}_kaggle_{class_name}_top_words.csv"),
        os.path.join(RESULTS_DIR, "attribution",
                     f"{model_key}_kaggle_{class_name}_scores.csv"),
    ]

    df = None
    for path in candidates:
        if os.path.exists(path):
            df = pd.read_csv(path)
            break

    if df is None or df.empty:
        return float("nan")

    word_col  = "word" if "word" in df.columns else "token"
    score_col = next(
        (c for c in ["mean_gradient", "mean_shap", "mean_importance"]
         if c in df.columns),
        None,
    )

    if word_col not in df.columns or score_col is None:
        return float("nan")

    df = df.sort_values(score_col, ascending=False)
    n  = len(df)

    if n < 2 * K:
        return float("nan")

    # Split by score rank: odd vs even rows — stable, deterministic split
    half_a = set(df.iloc[::2][word_col].head(K).tolist())
    half_b = set(df.iloc[1::2][word_col].head(K).tolist())
    union  = half_a | half_b

    if not union:
        return float("nan")

    return round(len(half_a & half_b) / len(union), 4)


# ── Main Analysis ─────────────────────────────────────────────────────────────

def run():
    """
    For every active model × class × K:
      - Load top-K words for Kaggle, Reddit, Twitter
      - Compute Jaccard (raw and artifact-filtered)
      - Compute clinical signal retention
      - Compute random baseline for context
    """
    rows           = []
    retention_rows = []

    for model_key in ACTIVE_MODELS:
        vocab_size   = VOCAB_SIZES.get(model_key, 50265)
        model_label  = MODEL_DISPLAY[model_key]

        print(f"\n{'='*55}")
        print(f"Model: {model_label}")
        print(f"{'='*55}")

        for class_name in CLASSES:
            print(f"\n  Class: {class_name.upper()}")

            for K in K_VALUES:
                random_baseline = expected_jaccard_random(K, vocab_size)

                # Load top-K word sets for all three platforms
                words = {
                    p: load_top_words(model_key, p, class_name, K,
                                      filter_artifacts=False)
                    for p in PLATFORMS
                }
                words_filtered = {
                    p: load_top_words(model_key, p, class_name, K,
                                      filter_artifacts=True)
                    for p in PLATFORMS
                }

                # Jaccard: Kaggle vs Reddit, Kaggle vs Twitter
                j_kr = jaccard(words["kaggle"], words["reddit"])
                j_kt = jaccard(words["kaggle"], words["twitter"])
                j_rt = jaccard(words["reddit"], words["twitter"])

                j_kr_f = jaccard(words_filtered["kaggle"], words_filtered["reddit"])
                j_kt_f = jaccard(words_filtered["kaggle"], words_filtered["twitter"])

                avg_j      = np.nanmean([j_kr, j_kt])
                avg_j_filt = np.nanmean([j_kr_f, j_kt_f])

                # Within-platform split-half baseline
                j_within = compute_within_platform_jaccard(model_key, class_name, K)

                if K == 10:  # Primary K reported in paper
                    missing_flag = not words["kaggle"] or not words["reddit"]
                    print(
                        f"    K=10 | J(Kgl,Reddit)={j_kr:.4f}  "
                        f"J(Kgl,Twitter)={j_kt:.4f}  "
                        f"J(within-Kgl)={j_within:.4f}  "
                        f"avg={avg_j:.4f}  "
                        f"baseline={random_baseline:.4f}"
                        + (" [NO DATA]" if missing_flag else "")
                    )

                rows.append({
                    "model":          model_key,
                    "class":          class_name,
                    "K":              K,
                    "vocab_size":     vocab_size,
                    "random_baseline":          random_baseline,
                    "j_within_kaggle":          j_within,
                    "j_kaggle_reddit":          j_kr,
                    "j_kaggle_twitter":         j_kt,
                    "j_reddit_twitter":         j_rt,
                    "j_kaggle_reddit_filtered": j_kr_f,
                    "j_kaggle_twitter_filtered":j_kt_f,
                    "avg_stability":            round(float(avg_j), 4),
                    "avg_stability_filtered":   round(float(avg_j_filt), 4),
                    "words_above_baseline":     (avg_j > random_baseline)
                                                if not np.isnan(avg_j) else False,
                })

            # Clinical signal retention at K=10 (fixed)
            for platform in PLATFORMS:
                w_set    = load_top_words(model_key, platform, class_name,
                                          K=10, filter_artifacts=False)
                w_filt   = load_top_words(model_key, platform, class_name,
                                          K=10, filter_artifacts=True)
                retention     = clinical_signal_retention(w_set)
                ret_filtered  = clinical_signal_retention(w_filt)
                retention_rows.append({
                    "model":                model_key,
                    "platform":             platform,
                    "class":                class_name,
                    "clinical_retention":   retention,
                    "clinical_ret_filtered":ret_filtered,
                    "n_words_found":        len(w_set),
                })

    return pd.DataFrame(rows), pd.DataFrame(retention_rows)


# ── Plotting ──────────────────────────────────────────────────────────────────

def plot_jaccard_with_baseline(df: pd.DataFrame):
    """
    Figure 6 (updated): Jaccard stability at K=10 with random baseline.
    One bar group per model, one bar per class.
    Random baseline shown as a dashed horizontal line.
    """
    df10 = df[df["K"] == 10].copy()
    if df10.empty:
        print("  No K=10 data to plot.")
        return

    classes     = CLASSES
    models      = ACTIVE_MODELS
    n_classes   = len(classes)
    bar_width   = 0.18
    group_gap   = 0.1
    colors      = ["#2196F3", "#4CAF50", "#FF9800", "#E91E63"]

    fig, axes = plt.subplots(1, 2, figsize=(16, 6), sharey=True)
    titles    = ["Kaggle vs Reddit", "Kaggle vs Twitter"]
    j_cols    = ["j_kaggle_reddit", "j_kaggle_twitter"]

    for ax, title, j_col in zip(axes, titles, j_cols):
        x = np.arange(n_classes) * (len(models) * bar_width + group_gap)

        for m_idx, model_key in enumerate(models):
            sub = df10[df10["model"] == model_key]
            vals = []
            for cls in classes:
                row = sub[sub["class"] == cls]
                vals.append(float(row[j_col].values[0]) if not row.empty else 0.0)

            bars = ax.bar(
                x + m_idx * bar_width, vals, bar_width,
                label=MODEL_DISPLAY[model_key],
                color=colors[m_idx], alpha=0.85, edgecolor="white", linewidth=0.5,
            )

        # Random baseline (model-average)
        baseline_vals = []
        for cls in classes:
            row = df10[df10["class"] == cls]
            if not row.empty:
                baseline_vals.append(float(row["random_baseline"].mean()))
        if baseline_vals:
            avg_baseline = np.mean(baseline_vals)
            ax.axhline(avg_baseline, color="gray", linestyle="--",
                       linewidth=1.5, alpha=0.8,
                       label=f"Random baseline (avg={avg_baseline:.4f})")

        ax.axhline(0.20, color="orange", linestyle=":",
                   linewidth=1, alpha=0.7, label="J=0.20 (borderline threshold)")

        ax.set_xticks(x + (len(models) - 1) * bar_width / 2)
        ax.set_xticklabels([c.capitalize() for c in classes], fontsize=10)
        ax.set_ylabel("Jaccard Similarity J(A, B)  [K=10]", fontsize=10)
        ax.set_title(title, fontsize=11, fontweight="bold")
        ax.set_ylim(0, 0.45)
        ax.grid(axis="y", alpha=0.3)
        ax.legend(fontsize=8, loc="upper right")

    fig.suptitle(
        "Cross-Platform Feature Attribution Stability — Jaccard Similarity at K=10\n"
        "All four models shown.  Values at or near the random baseline (dashed) "
        "indicate no transferable signal.",
        fontsize=12, fontweight="bold"
    )
    plt.tight_layout()
    out = os.path.join(FIGURES_DIR, "figure6_jaccard_with_baseline.png")
    plt.savefig(out, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"\n  Saved: {out}")


def plot_jaccard_k_sensitivity(df: pd.DataFrame):
    """
    Line plot: Jaccard vs K for each model × class (Kaggle vs Reddit).
    Confirms J=0.000 is not an artefact of K choice.
    """
    fig, axes = plt.subplots(1, len(CLASSES), figsize=(18, 5), sharey=True)
    colors    = ["#2196F3", "#4CAF50", "#FF9800", "#E91E63"]

    for ax, class_name in zip(axes, CLASSES):
        for m_idx, model_key in enumerate(ACTIVE_MODELS):
            sub   = df[(df["model"] == model_key) & (df["class"] == class_name)]
            sub   = sub.sort_values("K")
            if sub.empty:
                continue
            ax.plot(sub["K"], sub["j_kaggle_reddit"],
                    "o-", color=colors[m_idx], linewidth=1.8, markersize=5,
                    label=MODEL_DISPLAY[model_key])

        ax.set_title(class_name.capitalize(), fontsize=11, fontweight="bold")
        ax.set_xlabel("K (top-K tokens)", fontsize=9)
        ax.set_xticks(K_VALUES)
        ax.set_ylim(-0.01, 0.35)
        ax.axhline(0.0, color="red", linestyle="--", alpha=0.5, linewidth=1)
        ax.axhline(0.20, color="orange", linestyle=":", alpha=0.7, linewidth=1)
        ax.grid(alpha=0.3)
        if class_name == "normal":
            ax.legend(fontsize=8)

    axes[0].set_ylabel("Jaccard J(Kaggle, Reddit)", fontsize=10)
    fig.suptitle(
        "Jaccard Feature Stability vs K — Kaggle vs Reddit\n"
        "J=0.000 for clinical classes is stable across K=5–20 "
        "(not an artefact of the K=10 choice)",
        fontsize=11, fontweight="bold"
    )
    plt.tight_layout()
    out = os.path.join(FIGURES_DIR, "figure6b_jaccard_k_sensitivity.png")
    plt.savefig(out, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  Saved: {out}")


def plot_clinical_vocabulary_heatmap(ret_df: pd.DataFrame):
    """
    Heatmap: clinical vocabulary retention (fraction of top-10 tokens
    that are clinically meaningful) per model × platform × class.
    """
    if ret_df.empty:
        print("  No retention data to plot.")
        return

    pivot_rows = []
    for model_key in ACTIVE_MODELS:
        for platform in PLATFORMS:
            sub = ret_df[(ret_df["model"] == model_key) & (ret_df["platform"] == platform)]
            if sub.empty:
                continue
            row = {"Model-Platform": f"{MODEL_DISPLAY[model_key]}\n({platform})"}
            for cls in CLASSES:
                cls_row = sub[sub["class"] == cls]
                row[cls.capitalize()] = (
                    float(cls_row["clinical_retention"].values[0])
                    if not cls_row.empty else float("nan")
                )
            pivot_rows.append(row)

    if not pivot_rows:
        return

    hm = pd.DataFrame(pivot_rows).set_index("Model-Platform")

    fig, ax = plt.subplots(figsize=(10, 12))
    sns.heatmap(
        hm, annot=True, fmt=".2f", cmap="RdYlGn",
        vmin=0, vmax=1, ax=ax, linewidths=0.5,
        cbar_kws={"label": "Clinical Vocabulary Retention (K=10)"},
    )
    ax.set_title(
        "Clinical Vocabulary Retention in Top-10 Attribution Tokens\n"
        "Fraction of top-10 tokens that are clinically meaningful\n"
        "(higher = model relies on genuine clinical signal)",
        fontsize=11, fontweight="bold"
    )
    plt.tight_layout()
    out = os.path.join(FIGURES_DIR, "figure_clinical_vocabulary_heatmap.png")
    plt.savefig(out, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  Saved: {out}")


def print_summary_table(df: pd.DataFrame):
    """Print the J=0.000 summary table for the paper."""
    df10 = df[(df["K"] == 10)].copy()
    if df10.empty:
        print("  No K=10 data available.")
        return

    print(f"\n{'='*70}")
    print("JACCARD STABILITY TABLE (K=10, Kaggle vs Reddit) — For paper §4.8")
    print(f"{'='*70}")
    header = f"{'Model':<22}"
    for cls in CLASSES:
        header += f"  {cls.capitalize():>10}"
    header += f"  {'Random':>8}"
    print(header)
    print("-" * 70)

    for model_key in ACTIVE_MODELS:
        sub  = df10[df10["model"] == model_key]
        line = f"{MODEL_DISPLAY[model_key]:<22}"
        for cls in CLASSES:
            row = sub[sub["class"] == cls]
            val = float(row["j_kaggle_reddit"].values[0]) if not row.empty else float("nan")
            line += f"  {val:>10.4f}"
        baseline = float(sub["random_baseline"].mean()) if not sub.empty else float("nan")
        line += f"  {baseline:>8.4f}"
        print(line)

    print(f"\nNote: Random baseline is the expected J for random top-K selection.")
    print(f"      J at or below the baseline indicates complete feature instability.")
    print(f"      J=0.000 means ZERO overlap in top-10 attributed tokens.")


# ── Entry Point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("Jaccard Full Analysis — ALL FOUR MODELS (FIXED)")
    print(f"Active models: {ACTIVE_MODELS}")
    print(f"K values: {K_VALUES}")
    print("=" * 55)

    print("\nChecking for attribution CSV files...")
    missing = []
    for m in ACTIVE_MODELS:
        for p in PLATFORMS:
            for c in CLASSES:
                path1 = os.path.join(RESULTS_DIR, "shap",
                                     f"{m}_{p}_{c}_top_words.csv")
                path2 = os.path.join(RESULTS_DIR, "attribution",
                                     f"{m}_{p}_{c}_scores.csv")
                if not os.path.exists(path1) and not os.path.exists(path2):
                    missing.append(f"{m}/{p}/{c}")

    if missing:
        print(f"\nWARNING: Attribution CSVs not found for {len(missing)} combinations:")
        for m in missing[:10]:
            print(f"    {m}")
        if len(missing) > 10:
            print(f"    ... and {len(missing)-10} more")
        print("\nRun the following first:")
        print("    python src/code_A4_patch_attribution.py   (saves attribution CSVs)")
        print("    python src/shap_analysis.py               (also saves top_words CSVs)")
        print("\nContinuing with available files (missing models will have empty sets).\n")

    df, ret_df = run()

    if df.empty:
        print("\nNo attribution data found. Run code_A4_patch_attribution.py first.")
    else:
        df.to_csv(os.path.join(FAIRNESS_DIR, "jaccard_full_analysis.csv"), index=False)
        if not ret_df.empty:
            ret_df.to_csv(
                os.path.join(FAIRNESS_DIR, "clinical_signal_retention.csv"), index=False
            )

        plot_jaccard_with_baseline(df)
        plot_jaccard_k_sensitivity(df)
        plot_clinical_vocabulary_heatmap(ret_df)
        print_summary_table(df)

        print(f"\n{'='*55}")
        print("DONE. Outputs:")
        print(f"  {FAIRNESS_DIR}/jaccard_full_analysis.csv")
        print(f"  {FAIRNESS_DIR}/clinical_signal_retention.csv")
        print(f"  {FIGURES_DIR}/figure6_jaccard_with_baseline.png")
        print(f"  {FIGURES_DIR}/figure6b_jaccard_k_sensitivity.png")
        print(f"  {FIGURES_DIR}/figure_clinical_vocabulary_heatmap.png")
